version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - /Users/zhammack/Downloads/cs/connect4/backend:/app/backend
      - /Users/zhammack/Downloads/cs/connect4/game:/app/game

    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase


  frontend:
    image: frontend
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    command: ["serve", "-s", "build", "-l", "3000"]
    volumes:
      - /Users/zhammack/Downloads/cs/connect4/frontend/src:/app/frontend/src
      - /Users/zhammack/Downloads/cs/connect4/frontend/node_modules:/app/frontend/node_modules

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: